### ISSUE TITLE
How to deal with it

### ISSUE THREAD

**Issue by ZYX223** [numamma/numamma#10]
numap_sampling_read_start error : libnumap: error when calling perf_event_open: Permission denied

**Comment by trahay** [comment]
This is probably due to system restriction on perf_event.
You can try setting /proc/sys/kernel/perf_event_paranoid to 1 :
```
$ echo 1 > /proc/sys/kernel/perf_event_paranoid
```

**Comment by ZYX223** [comment]
When I run "install_everything.sh",I met a problem:
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'numap' found
Call Stack (most recent call first):
  cmake/Findnumap.cmake:16 (pkg_search_module)
  CMakeLists.txt:28 (find_package)


CMake Error at CMakeLists.txt:32 (message):
  numap not found


-- Configuring incomplete, errors occurred!

How to deal with it

**Comment by ZYX223** [comment]
Hello , when I run the application cg.B.x ,I find most of the sample do not match a known memory buffer, like this:875471 samples (including 795384 samples that do not match a known memory buffer / 90.852127%)
I want to the thread id and the timestamp access the Local RAM, but I cannot find these information in the callsite_dump_.dat

**Comment by trahay** [comment]
The number of unmatched samples is indeed quite high. This may be due to the application doing lots of memory accesses on the stack. Detecting the boundaries of the stack may be buggous in numamma.

You can get more information on unmatched samples by passing -u to numamma. This will dump the unmatched samples to a file. I just pushed a modification (see commit bbaef01) that gives additionnal information for unmatched samples.

If you want the thread id and timestamp of Local RAM access, you can run the application like this:

```
$ numamma -d -u ./bin/cg.A.x 
```
Then read the `callsite_dump_*.dat` and `unmatched_samples.log`.

Ideally, we could add an option to `numamma` that reports statistics per thread.

**Comment by ZYX223** [comment]
OK ,thanks.It is very useful, and I don't know what's the LFB hit.

When I run "numamma -d -u ./sp.B.x" ,it is failed.It return me this:
: /home/zyx/numamma-master/numamma/src/mem_sampling.c:719: __copy_buffer: Assertion 'event->type < 20' failed.
